/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as GroupadsaGroupIdRouteImport } from './routes/groupadsa.$groupId'
import { Route as GroupIdRouteRouteImport } from './routes/group/$id/route'
import { Route as GroupIdIndexRouteImport } from './routes/group/$id/index'
import { Route as GroupIdChannelChannelIdIndexRouteImport } from './routes/group/$id/channel/$channelId/index'

const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupadsaGroupIdRoute = GroupadsaGroupIdRouteImport.update({
  id: '/groupadsa/$groupId',
  path: '/groupadsa/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdRouteRoute = GroupIdRouteRouteImport.update({
  id: '/group/$id',
  path: '/group/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdIndexRoute = GroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupIdRouteRoute,
} as any)
const GroupIdChannelChannelIdIndexRoute =
  GroupIdChannelChannelIdIndexRouteImport.update({
    id: '/channel/$channelId/',
    path: '/channel/$channelId/',
    getParentRoute: () => GroupIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todo': typeof TodoRoute
  '/group/$id': typeof GroupIdRouteRouteWithChildren
  '/groupadsa/$groupId': typeof GroupadsaGroupIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/group/$id/': typeof GroupIdIndexRoute
  '/group/$id/channel/$channelId': typeof GroupIdChannelChannelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todo': typeof TodoRoute
  '/groupadsa/$groupId': typeof GroupadsaGroupIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/group/$id': typeof GroupIdIndexRoute
  '/group/$id/channel/$channelId': typeof GroupIdChannelChannelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todo': typeof TodoRoute
  '/group/$id': typeof GroupIdRouteRouteWithChildren
  '/groupadsa/$groupId': typeof GroupadsaGroupIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/group/$id/': typeof GroupIdIndexRoute
  '/group/$id/channel/$channelId/': typeof GroupIdChannelChannelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/todo'
    | '/group/$id'
    | '/groupadsa/$groupId'
    | '/join/$token'
    | '/group/$id/'
    | '/group/$id/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/todo'
    | '/groupadsa/$groupId'
    | '/join/$token'
    | '/group/$id'
    | '/group/$id/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/todo'
    | '/group/$id'
    | '/groupadsa/$groupId'
    | '/join/$token'
    | '/group/$id/'
    | '/group/$id/channel/$channelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TodoRoute: typeof TodoRoute
  GroupIdRouteRoute: typeof GroupIdRouteRouteWithChildren
  GroupadsaGroupIdRoute: typeof GroupadsaGroupIdRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupadsa/$groupId': {
      id: '/groupadsa/$groupId'
      path: '/groupadsa/$groupId'
      fullPath: '/groupadsa/$groupId'
      preLoaderRoute: typeof GroupadsaGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id': {
      id: '/group/$id'
      path: '/group/$id'
      fullPath: '/group/$id'
      preLoaderRoute: typeof GroupIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/': {
      id: '/group/$id/'
      path: '/'
      fullPath: '/group/$id/'
      preLoaderRoute: typeof GroupIdIndexRouteImport
      parentRoute: typeof GroupIdRouteRoute
    }
    '/group/$id/channel/$channelId/': {
      id: '/group/$id/channel/$channelId/'
      path: '/channel/$channelId'
      fullPath: '/group/$id/channel/$channelId'
      preLoaderRoute: typeof GroupIdChannelChannelIdIndexRouteImport
      parentRoute: typeof GroupIdRouteRoute
    }
  }
}

interface GroupIdRouteRouteChildren {
  GroupIdIndexRoute: typeof GroupIdIndexRoute
  GroupIdChannelChannelIdIndexRoute: typeof GroupIdChannelChannelIdIndexRoute
}

const GroupIdRouteRouteChildren: GroupIdRouteRouteChildren = {
  GroupIdIndexRoute: GroupIdIndexRoute,
  GroupIdChannelChannelIdIndexRoute: GroupIdChannelChannelIdIndexRoute,
}

const GroupIdRouteRouteWithChildren = GroupIdRouteRoute._addFileChildren(
  GroupIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TodoRoute: TodoRoute,
  GroupIdRouteRoute: GroupIdRouteRouteWithChildren,
  GroupadsaGroupIdRoute: GroupadsaGroupIdRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
