/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutIndexRouteImport } from './routes/layout/index'
import { Route as LayoutLayoutRouteImport } from './routes/layout/_layout'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as GroupIdIndexRouteImport } from './routes/group/$id/index'
import { Route as GroupIdTesteRouteImport } from './routes/group/$id/teste'
import { Route as GroupIdChannelChannelIdIndexRouteImport } from './routes/group/$id/channel/$channelId/index'

const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLayoutRoute = LayoutLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdIndexRoute = GroupIdIndexRouteImport.update({
  id: '/group/$id/',
  path: '/group/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdTesteRoute = GroupIdTesteRouteImport.update({
  id: '/group/$id/teste',
  path: '/group/$id/teste',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdChannelChannelIdIndexRoute =
  GroupIdChannelChannelIdIndexRouteImport.update({
    id: '/group/$id/channel/$channelId/',
    path: '/group/$id/channel/$channelId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/layout': typeof LayoutLayoutRoute
  '/login': typeof LoginRoute
  '/todo': typeof TodoRoute
  '/join/$token': typeof JoinTokenRoute
  '/layout/': typeof LayoutIndexRoute
  '/group/$id/teste': typeof GroupIdTesteRoute
  '/group/$id': typeof GroupIdIndexRoute
  '/group/$id/channel/$channelId': typeof GroupIdChannelChannelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todo': typeof TodoRoute
  '/join/$token': typeof JoinTokenRoute
  '/layout': typeof LayoutIndexRoute
  '/group/$id/teste': typeof GroupIdTesteRoute
  '/group/$id': typeof GroupIdIndexRoute
  '/group/$id/channel/$channelId': typeof GroupIdChannelChannelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/todo': typeof TodoRoute
  '/join/$token': typeof JoinTokenRoute
  '/layout/_layout': typeof LayoutLayoutRoute
  '/layout/': typeof LayoutIndexRoute
  '/group/$id/teste': typeof GroupIdTesteRoute
  '/group/$id/': typeof GroupIdIndexRoute
  '/group/$id/channel/$channelId/': typeof GroupIdChannelChannelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/layout'
    | '/login'
    | '/todo'
    | '/join/$token'
    | '/layout/'
    | '/group/$id/teste'
    | '/group/$id'
    | '/group/$id/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/todo'
    | '/join/$token'
    | '/layout'
    | '/group/$id/teste'
    | '/group/$id'
    | '/group/$id/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/layout'
    | '/login'
    | '/todo'
    | '/join/$token'
    | '/layout/_layout'
    | '/layout/'
    | '/group/$id/teste'
    | '/group/$id/'
    | '/group/$id/channel/$channelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  TodoRoute: typeof TodoRoute
  JoinTokenRoute: typeof JoinTokenRoute
  GroupIdTesteRoute: typeof GroupIdTesteRoute
  GroupIdIndexRoute: typeof GroupIdIndexRoute
  GroupIdChannelChannelIdIndexRoute: typeof GroupIdChannelChannelIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout/': {
      id: '/layout/'
      path: '/'
      fullPath: '/layout/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/layout/_layout': {
      id: '/layout/_layout'
      path: ''
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/': {
      id: '/group/$id/'
      path: '/group/$id'
      fullPath: '/group/$id'
      preLoaderRoute: typeof GroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/teste': {
      id: '/group/$id/teste'
      path: '/group/$id/teste'
      fullPath: '/group/$id/teste'
      preLoaderRoute: typeof GroupIdTesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$id/channel/$channelId/': {
      id: '/group/$id/channel/$channelId/'
      path: '/group/$id/channel/$channelId'
      fullPath: '/group/$id/channel/$channelId'
      preLoaderRoute: typeof GroupIdChannelChannelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutLayoutRoute: typeof LayoutLayoutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLayoutRoute: LayoutLayoutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  TodoRoute: TodoRoute,
  JoinTokenRoute: JoinTokenRoute,
  GroupIdTesteRoute: GroupIdTesteRoute,
  GroupIdIndexRoute: GroupIdIndexRoute,
  GroupIdChannelChannelIdIndexRoute: GroupIdChannelChannelIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
